[package]
name = "dom_smoothie"
version = "0.1.0"
edition = "2021"
exclude = [".*", "test-pagess"]

[dependencies]
dom_query = {version = "0.10.0"}
tendril = {version = "0.4.3"}
once_cell = { version = "1" }

regex = {version = "1.11.1"}
serde = {version = "1.0.214", features = ["derive"]}
serde_json = {version = "1.0.132"}
gjson = {version = "0.8.1"}
html-escape = "0.2.13"
flagset = "0.4.6"
url = "2.5.3"
unicode-segmentation = "1.10.1"
thiserror = "2.0"