[package]
name = "dom_readability"
version = "0.1.0"
edition = "2021"

[dependencies]
dom_query = {path ="../dom_query"}
tendril = {version = "0.4.3"}
once_cell = { version = "1" }

regex = {version = "1.11"}
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
gjson = {version = "0.8.1"}
html-escape = "0.2.13"