[package]
name = "dom_smoothie_cli"
version = "0.1.0"
edition = "2021"
description = "A reference cli for dom_smoothie"
authors = ["niklak <morgenpurple@gmail.com>"]


[dependencies]
dom_smoothie = {path = "./.."}
clap = {version = "4.5.23", features = ["derive"]}