name: Build and Release Binaries

on:
  release:
    types: [published, prereleased]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Add Target (Linux and macOS)
      if: runner.os != 'Windows'
      run: rustup target add $(rustc --print target-triple)

    - name: Install Dependencies (Windows Only)
      if: runner.os == 'Windows'
      run: |
        choco install mingw
        echo "Add mingw to PATH"
        echo "::add-path::C:\\tools\\mingw64\\bin"

    - name: Build Binary
      run: cargo build --release
      working-directory: dom_smoothie_cli

    - name: Prepare Binary
      run: |
        mkdir -p binaries
        cp dom_smoothie_cli/target/release/dom_smoothie_cli binaries/dom_smoothie_cli-${{ matrix.os }}

    - name: Upload Binaries to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: binaries/dom_smoothie_cli-${{ matrix.os }}
        asset_name: dom_smoothie_cli-${{ matrix.os }}
        asset_content_type: application/octet-stream
