name: Build and Release Binaries

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"


permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and upload

    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            src_file: dom_smoothie_cli
            dst_file: dom_smoothie_cli-x86_64-unknown-linux-gnu

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
            src_file: dom_smoothie_cli
            dst_file: dom_smoothie_cli-x86_64-apple-darwin
        
          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
            src_file: dom_smoothie_cli.exe
            dst_file: dom_smoothie_cli-x86_64-pc-windows-gnu.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Rust
        # Or @nightly if you want
        uses: dtolnay/rust-toolchain@stable
        # Arguments to pass in
        with:
          # Make Rust compile to our target (defined in the matrix)
          targets: ${{ matrix.target }}


      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: dom_smoothie_cli
    
      - name: Prepare Binary (Linux and macOS)
        run: |
            mkdir -p binaries
            cp target/${{ matrix.target }}/release/${{ matrix.src_file }} binaries/${{ matrix.dst_file }}
