name: Build and Release Binaries

on:
  release:
    types: [published, prereleased]

jobs:
  build:
    name: Build Binaries for Multiple Platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Add Target
      run: rustup target add ${{ matrix.target }}

    - name: Build Binary
      run: cargo build --release --target ${{ matrix.target }}
      working-directory: dom_smoothie_cli

    - name: Prepare Binary
      run: |
        mkdir -p binaries
        cp target/${{ matrix.target }}/release/dom_smoothie_cli binaries/dom_smoothie_cli-${{ matrix.target }}

    - name: Upload Binaries to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: binaries/dom_smoothie_cli-${{ matrix.target }}
        asset_name: dom_smoothie_cli-${{ matrix.target }}
        asset_content_type: application/octet-stream
