name: Build and Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and upload

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            src_file: dom_smoothie_cli
            dst_file: dom_smoothie_cli-x86_64-unknown-linux-gnu-${{ github.ref_name }}

          - os: macos-latest
            target: x86_64-apple-darwin
            src_file: dom_smoothie_cli
            dst_file: dom_smoothie_cli-x86_64-apple-darwin-${{ github.ref_name }}

          - os: windows-latest
            target: x86_64-pc-windows-gnu
            src_file: dom_smoothie_cli.exe
            dst_file: dom_smoothie_cli-x86_64-pc-windows-gnu-${{ github.ref_name }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: dom_smoothie_cli

      - name: Prepare Archive
        run: |
          zip -j ${{ matrix.dst_file }}.zip target/${{ matrix.target }}/release/${{ matrix.src_file }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.dst_file }}.zip
