name: Build and Release Binaries

on:
  release:
    types: [published, prereleased]


permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and upload

    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            src_file: dom_smoothie_cli
            dst_file: dom_smoothie_cli-${{ github.ref_name }}-x86_64-unknown-linux-gnu
            

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
            src_file: dom_smoothie_cli
            dst_file: dom_smoothie_cli-${{ github.ref_name }}-x86_64-apple-darwin
        
          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
            src_file: dom_smoothie_cli.exe
            dst_file: dom_smoothie_cli-${{ github.ref_name }}-x86_64-pc-windows-gnu.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        # Or @nightly if you want
        uses: dtolnay/rust-toolchain@stable
        # Arguments to pass in
        with:
          # Make Rust compile to our target (defined in the matrix)
          targets: ${{ matrix.target }}


      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: dom_smoothie_cli
    
      - name: Prepare Binary
        run: |
            mkdir -p binaries
            cp target/${{ matrix.target }}/release/${{ matrix.src_file }} binaries/${{ matrix.dst_file }}

    
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            binaries/${{ matrix.dst_file }}